// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: game.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GameStateChangeEvent_Type int32

const (
	GameStateChangeEvent_Ready GameStateChangeEvent_Type = 0
	GameStateChangeEvent_End   GameStateChangeEvent_Type = 1
)

// Enum value maps for GameStateChangeEvent_Type.
var (
	GameStateChangeEvent_Type_name = map[int32]string{
		0: "Ready",
		1: "End",
	}
	GameStateChangeEvent_Type_value = map[string]int32{
		"Ready": 0,
		"End":   1,
	}
)

func (x GameStateChangeEvent_Type) Enum() *GameStateChangeEvent_Type {
	p := new(GameStateChangeEvent_Type)
	*p = x
	return p
}

func (x GameStateChangeEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStateChangeEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (GameStateChangeEvent_Type) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x GameStateChangeEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStateChangeEvent_Type.Descriptor instead.
func (GameStateChangeEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5, 0}
}

type ClientMatchStatusRequest_Type int32

const (
	ClientMatchStatusRequest_Ready ClientMatchStatusRequest_Type = 0
	ClientMatchStatusRequest_End   ClientMatchStatusRequest_Type = 1
)

// Enum value maps for ClientMatchStatusRequest_Type.
var (
	ClientMatchStatusRequest_Type_name = map[int32]string{
		0: "Ready",
		1: "End",
	}
	ClientMatchStatusRequest_Type_value = map[string]int32{
		"Ready": 0,
		"End":   1,
	}
)

func (x ClientMatchStatusRequest_Type) Enum() *ClientMatchStatusRequest_Type {
	p := new(ClientMatchStatusRequest_Type)
	*p = x
	return p
}

func (x ClientMatchStatusRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMatchStatusRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (ClientMatchStatusRequest_Type) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x ClientMatchStatusRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMatchStatusRequest_Type.Descriptor instead.
func (ClientMatchStatusRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6, 0}
}

type GameResultEvent_Type int32

const (
	GameResultEvent_Success GameResultEvent_Type = 0
	GameResultEvent_Failure GameResultEvent_Type = 1
)

// Enum value maps for GameResultEvent_Type.
var (
	GameResultEvent_Type_name = map[int32]string{
		0: "Success",
		1: "Failure",
	}
	GameResultEvent_Type_value = map[string]int32{
		"Success": 0,
		"Failure": 1,
	}
)

func (x GameResultEvent_Type) Enum() *GameResultEvent_Type {
	p := new(GameResultEvent_Type)
	*p = x
	return p
}

func (x GameResultEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameResultEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[2].Descriptor()
}

func (GameResultEvent_Type) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[2]
}

func (x GameResultEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameResultEvent_Type.Descriptor instead.
func (GameResultEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7, 0}
}

type ChatSessionEvent_Type int32

const (
	ChatSessionEvent_Begin ChatSessionEvent_Type = 0
	ChatSessionEvent_End   ChatSessionEvent_Type = 1
)

// Enum value maps for ChatSessionEvent_Type.
var (
	ChatSessionEvent_Type_name = map[int32]string{
		0: "Begin",
		1: "End",
	}
	ChatSessionEvent_Type_value = map[string]int32{
		"Begin": 0,
		"End":   1,
	}
)

func (x ChatSessionEvent_Type) Enum() *ChatSessionEvent_Type {
	p := new(ChatSessionEvent_Type)
	*p = x
	return p
}

func (x ChatSessionEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatSessionEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[3].Descriptor()
}

func (ChatSessionEvent_Type) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[3]
}

func (x ChatSessionEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatSessionEvent_Type.Descriptor instead.
func (ChatSessionEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8, 0}
}

type MatchStateChangeEvent_Type int32

const (
	MatchStateChangeEvent_Ready     MatchStateChangeEvent_Type = 0
	MatchStateChangeEvent_GameBegin MatchStateChangeEvent_Type = 1
	MatchStateChangeEvent_GameEnd   MatchStateChangeEvent_Type = 2
	MatchStateChangeEvent_Exit      MatchStateChangeEvent_Type = 3
	MatchStateChangeEvent_EnterChat MatchStateChangeEvent_Type = 4
	MatchStateChangeEvent_ExitChat  MatchStateChangeEvent_Type = 5
)

// Enum value maps for MatchStateChangeEvent_Type.
var (
	MatchStateChangeEvent_Type_name = map[int32]string{
		0: "Ready",
		1: "GameBegin",
		2: "GameEnd",
		3: "Exit",
		4: "EnterChat",
		5: "ExitChat",
	}
	MatchStateChangeEvent_Type_value = map[string]int32{
		"Ready":     0,
		"GameBegin": 1,
		"GameEnd":   2,
		"Exit":      3,
		"EnterChat": 4,
		"ExitChat":  5,
	}
)

func (x MatchStateChangeEvent_Type) Enum() *MatchStateChangeEvent_Type {
	p := new(MatchStateChangeEvent_Type)
	*p = x
	return p
}

func (x MatchStateChangeEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStateChangeEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[4].Descriptor()
}

func (MatchStateChangeEvent_Type) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[4]
}

func (x MatchStateChangeEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStateChangeEvent_Type.Descriptor instead.
func (MatchStateChangeEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10, 0}
}

type UserAKillEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId uint32 `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
}

func (x *UserAKillEvent) Reset() {
	*x = UserAKillEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAKillEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAKillEvent) ProtoMessage() {}

func (x *UserAKillEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAKillEvent.ProtoReflect.Descriptor instead.
func (*UserAKillEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *UserAKillEvent) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	ObjectId uint32    `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *Object) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Object) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type UserBMoveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To *Position `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *UserBMoveEvent) Reset() {
	*x = UserBMoveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBMoveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBMoveEvent) ProtoMessage() {}

func (x *UserBMoveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBMoveEvent.ProtoReflect.Descriptor instead.
func (*UserBMoveEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *UserBMoveEvent) GetTo() *Position {
	if x != nil {
		return x.To
	}
	return nil
}

type UserBInitEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThatObjectIsMe uint32 `protobuf:"varint,1,opt,name=that_object_is_me,json=thatObjectIsMe,proto3" json:"that_object_is_me,omitempty"`
}

func (x *UserBInitEvent) Reset() {
	*x = UserBInitEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBInitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBInitEvent) ProtoMessage() {}

func (x *UserBInitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBInitEvent.ProtoReflect.Descriptor instead.
func (*UserBInitEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *UserBInitEvent) GetThatObjectIsMe() uint32 {
	if x != nil {
		return x.ThatObjectIsMe
	}
	return 0
}

type GameStateChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type GameStateChangeEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=GameStateChangeEvent_Type" json:"type,omitempty"`
}

func (x *GameStateChangeEvent) Reset() {
	*x = GameStateChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStateChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateChangeEvent) ProtoMessage() {}

func (x *GameStateChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateChangeEvent.ProtoReflect.Descriptor instead.
func (*GameStateChangeEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameStateChangeEvent) GetType() GameStateChangeEvent_Type {
	if x != nil {
		return x.Type
	}
	return GameStateChangeEvent_Ready
}

type ClientMatchStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ClientMatchStatusRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=ClientMatchStatusRequest_Type" json:"type,omitempty"`
}

func (x *ClientMatchStatusRequest) Reset() {
	*x = ClientMatchStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMatchStatusRequest) ProtoMessage() {}

func (x *ClientMatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMatchStatusRequest.ProtoReflect.Descriptor instead.
func (*ClientMatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *ClientMatchStatusRequest) GetType() ClientMatchStatusRequest_Type {
	if x != nil {
		return x.Type
	}
	return ClientMatchStatusRequest_Ready
}

type GameResultEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type GameResultEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=GameResultEvent_Type" json:"type,omitempty"`
}

func (x *GameResultEvent) Reset() {
	*x = GameResultEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResultEvent) ProtoMessage() {}

func (x *GameResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResultEvent.ProtoReflect.Descriptor instead.
func (*GameResultEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameResultEvent) GetType() GameResultEvent_Type {
	if x != nil {
		return x.Type
	}
	return GameResultEvent_Success
}

type ChatSessionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ChatSessionEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=ChatSessionEvent_Type" json:"type,omitempty"`
}

func (x *ChatSessionEvent) Reset() {
	*x = ChatSessionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSessionEvent) ProtoMessage() {}

func (x *ChatSessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSessionEvent.ProtoReflect.Descriptor instead.
func (*ChatSessionEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *ChatSessionEvent) GetType() ChatSessionEvent_Type {
	if x != nil {
		return x.Type
	}
	return ChatSessionEvent_Begin
}

type UpdateObjectsLocationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *UpdateObjectsLocationEvent) Reset() {
	*x = UpdateObjectsLocationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateObjectsLocationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectsLocationEvent) ProtoMessage() {}

func (x *UpdateObjectsLocationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectsLocationEvent.ProtoReflect.Descriptor instead.
func (*UpdateObjectsLocationEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateObjectsLocationEvent) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type MatchStateChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MatchStateChangeEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=MatchStateChangeEvent_Type" json:"type,omitempty"`
}

func (x *MatchStateChangeEvent) Reset() {
	*x = MatchStateChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStateChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStateChangeEvent) ProtoMessage() {}

func (x *MatchStateChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStateChangeEvent.ProtoReflect.Descriptor instead.
func (*MatchStateChangeEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *MatchStateChangeEvent) GetType() MatchStateChangeEvent_Type {
	if x != nil {
		return x.Type
	}
	return MatchStateChangeEvent_Ready
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0e,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x4b, 0x69, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x08, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x79, 0x22, 0x4c, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x25, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x3b,
	0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x29, 0x0a, 0x11, 0x74, 0x68, 0x61, 0x74, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x69, 0x73, 0x5f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x74, 0x68, 0x61,
	0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x73, 0x4d, 0x65, 0x22, 0x62, 0x0a, 0x14, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x52,
	0x65, 0x61, 0x64, 0x79, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x10, 0x01, 0x22,
	0x6a, 0x0a, 0x18, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x1a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x10, 0x01, 0x22, 0x5e, 0x0a, 0x0f, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x29,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x20, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x01, 0x22, 0x5a, 0x0a, 0x10, 0x43,
	0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x45, 0x6e, 0x64, 0x10, 0x01, 0x22, 0x3f, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x15, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x54, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x52,
	0x65, 0x61, 0x64, 0x79, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64,
	0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x78, 0x69, 0x74, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x78, 0x69, 0x74, 0x43, 0x68, 0x61, 0x74, 0x10, 0x05, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_game_proto_goTypes = []interface{}{
	(GameStateChangeEvent_Type)(0),     // 0: GameStateChangeEvent.Type
	(ClientMatchStatusRequest_Type)(0), // 1: ClientMatchStatusRequest.Type
	(GameResultEvent_Type)(0),          // 2: GameResultEvent.Type
	(ChatSessionEvent_Type)(0),         // 3: ChatSessionEvent.Type
	(MatchStateChangeEvent_Type)(0),    // 4: MatchStateChangeEvent.Type
	(*UserAKillEvent)(nil),             // 5: UserAKillEvent
	(*Position)(nil),                   // 6: Position
	(*Object)(nil),                     // 7: Object
	(*UserBMoveEvent)(nil),             // 8: UserBMoveEvent
	(*UserBInitEvent)(nil),             // 9: UserBInitEvent
	(*GameStateChangeEvent)(nil),       // 10: GameStateChangeEvent
	(*ClientMatchStatusRequest)(nil),   // 11: ClientMatchStatusRequest
	(*GameResultEvent)(nil),            // 12: GameResultEvent
	(*ChatSessionEvent)(nil),           // 13: ChatSessionEvent
	(*UpdateObjectsLocationEvent)(nil), // 14: UpdateObjectsLocationEvent
	(*MatchStateChangeEvent)(nil),      // 15: MatchStateChangeEvent
}
var file_game_proto_depIdxs = []int32{
	6, // 0: Object.position:type_name -> Position
	6, // 1: UserBMoveEvent.to:type_name -> Position
	0, // 2: GameStateChangeEvent.type:type_name -> GameStateChangeEvent.Type
	1, // 3: ClientMatchStatusRequest.type:type_name -> ClientMatchStatusRequest.Type
	2, // 4: GameResultEvent.type:type_name -> GameResultEvent.Type
	3, // 5: ChatSessionEvent.type:type_name -> ChatSessionEvent.Type
	7, // 6: UpdateObjectsLocationEvent.objects:type_name -> Object
	4, // 7: MatchStateChangeEvent.type:type_name -> MatchStateChangeEvent.Type
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAKillEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBMoveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBInitEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStateChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMatchStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameResultEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatSessionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateObjectsLocationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStateChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
