// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: match.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MatchMakingRequest_Type int32

const (
	MatchMakingRequest_Begin     MatchMakingRequest_Type = 0
	MatchMakingRequest_Cancel    MatchMakingRequest_Type = 1
	MatchMakingRequest_Accept    MatchMakingRequest_Type = 2
	MatchMakingRequest_NotAccept MatchMakingRequest_Type = 3
)

// Enum value maps for MatchMakingRequest_Type.
var (
	MatchMakingRequest_Type_name = map[int32]string{
		0: "Begin",
		1: "Cancel",
		2: "Accept",
		3: "NotAccept",
	}
	MatchMakingRequest_Type_value = map[string]int32{
		"Begin":     0,
		"Cancel":    1,
		"Accept":    2,
		"NotAccept": 3,
	}
)

func (x MatchMakingRequest_Type) Enum() *MatchMakingRequest_Type {
	p := new(MatchMakingRequest_Type)
	*p = x
	return p
}

func (x MatchMakingRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMakingRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_match_proto_enumTypes[0].Descriptor()
}

func (MatchMakingRequest_Type) Type() protoreflect.EnumType {
	return &file_match_proto_enumTypes[0]
}

func (x MatchMakingRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMakingRequest_Type.Descriptor instead.
func (MatchMakingRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{0, 0}
}

type MatchMakingResponse_Type int32

const (
	MatchMakingResponse_Available    MatchMakingResponse_Type = 0
	MatchMakingResponse_NotAvailable MatchMakingResponse_Type = 1
)

// Enum value maps for MatchMakingResponse_Type.
var (
	MatchMakingResponse_Type_name = map[int32]string{
		0: "Available",
		1: "NotAvailable",
	}
	MatchMakingResponse_Type_value = map[string]int32{
		"Available":    0,
		"NotAvailable": 1,
	}
)

func (x MatchMakingResponse_Type) Enum() *MatchMakingResponse_Type {
	p := new(MatchMakingResponse_Type)
	*p = x
	return p
}

func (x MatchMakingResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMakingResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_match_proto_enumTypes[1].Descriptor()
}

func (MatchMakingResponse_Type) Type() protoreflect.EnumType {
	return &file_match_proto_enumTypes[1]
}

func (x MatchMakingResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMakingResponse_Type.Descriptor instead.
func (MatchMakingResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{1, 0}
}

type MatchMakingResponse_Role int32

const (
	MatchMakingResponse_A MatchMakingResponse_Role = 0
	MatchMakingResponse_B MatchMakingResponse_Role = 1
)

// Enum value maps for MatchMakingResponse_Role.
var (
	MatchMakingResponse_Role_name = map[int32]string{
		0: "A",
		1: "B",
	}
	MatchMakingResponse_Role_value = map[string]int32{
		"A": 0,
		"B": 1,
	}
)

func (x MatchMakingResponse_Role) Enum() *MatchMakingResponse_Role {
	p := new(MatchMakingResponse_Role)
	*p = x
	return p
}

func (x MatchMakingResponse_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMakingResponse_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_match_proto_enumTypes[2].Descriptor()
}

func (MatchMakingResponse_Role) Type() protoreflect.EnumType {
	return &file_match_proto_enumTypes[2]
}

func (x MatchMakingResponse_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMakingResponse_Role.Descriptor instead.
func (MatchMakingResponse_Role) EnumDescriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{1, 1}
}

type MatchStateChangeEvent_Type int32

const (
	MatchStateChangeEvent_MatchPending  MatchStateChangeEvent_Type = 0
	MatchStateChangeEvent_MatchAccepted MatchStateChangeEvent_Type = 1
	MatchStateChangeEvent_GameReady     MatchStateChangeEvent_Type = 2
	MatchStateChangeEvent_GameBegin     MatchStateChangeEvent_Type = 3
	MatchStateChangeEvent_GameEnd       MatchStateChangeEvent_Type = 4
	MatchStateChangeEvent_ChatPending   MatchStateChangeEvent_Type = 5
	MatchStateChangeEvent_ChatReady     MatchStateChangeEvent_Type = 6
	MatchStateChangeEvent_ChatBegin     MatchStateChangeEvent_Type = 7
	MatchStateChangeEvent_ChatEnd       MatchStateChangeEvent_Type = 8
	MatchStateChangeEvent_MatchExit     MatchStateChangeEvent_Type = 9
)

// Enum value maps for MatchStateChangeEvent_Type.
var (
	MatchStateChangeEvent_Type_name = map[int32]string{
		0: "MatchPending",
		1: "MatchAccepted",
		2: "GameReady",
		3: "GameBegin",
		4: "GameEnd",
		5: "ChatPending",
		6: "ChatReady",
		7: "ChatBegin",
		8: "ChatEnd",
		9: "MatchExit",
	}
	MatchStateChangeEvent_Type_value = map[string]int32{
		"MatchPending":  0,
		"MatchAccepted": 1,
		"GameReady":     2,
		"GameBegin":     3,
		"GameEnd":       4,
		"ChatPending":   5,
		"ChatReady":     6,
		"ChatBegin":     7,
		"ChatEnd":       8,
		"MatchExit":     9,
	}
)

func (x MatchStateChangeEvent_Type) Enum() *MatchStateChangeEvent_Type {
	p := new(MatchStateChangeEvent_Type)
	*p = x
	return p
}

func (x MatchStateChangeEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStateChangeEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_match_proto_enumTypes[3].Descriptor()
}

func (MatchStateChangeEvent_Type) Type() protoreflect.EnumType {
	return &file_match_proto_enumTypes[3]
}

func (x MatchStateChangeEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStateChangeEvent_Type.Descriptor instead.
func (MatchStateChangeEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{2, 0}
}

type MatchMakingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MatchMakingRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=MatchMakingRequest_Type" json:"type,omitempty"`
}

func (x *MatchMakingRequest) Reset() {
	*x = MatchMakingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchMakingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMakingRequest) ProtoMessage() {}

func (x *MatchMakingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMakingRequest.ProtoReflect.Descriptor instead.
func (*MatchMakingRequest) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{0}
}

func (x *MatchMakingRequest) GetType() MatchMakingRequest_Type {
	if x != nil {
		return x.Type
	}
	return MatchMakingRequest_Begin
}

type MatchMakingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MatchMakingResponse_Type `protobuf:"varint,1,opt,name=type,proto3,enum=MatchMakingResponse_Type" json:"type,omitempty"`
	Role MatchMakingResponse_Role `protobuf:"varint,2,opt,name=role,proto3,enum=MatchMakingResponse_Role" json:"role,omitempty"`
}

func (x *MatchMakingResponse) Reset() {
	*x = MatchMakingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchMakingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMakingResponse) ProtoMessage() {}

func (x *MatchMakingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMakingResponse.ProtoReflect.Descriptor instead.
func (*MatchMakingResponse) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{1}
}

func (x *MatchMakingResponse) GetType() MatchMakingResponse_Type {
	if x != nil {
		return x.Type
	}
	return MatchMakingResponse_Available
}

func (x *MatchMakingResponse) GetRole() MatchMakingResponse_Role {
	if x != nil {
		return x.Role
	}
	return MatchMakingResponse_A
}

type MatchStateChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MatchStateChangeEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=MatchStateChangeEvent_Type" json:"type,omitempty"`
}

func (x *MatchStateChangeEvent) Reset() {
	*x = MatchStateChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStateChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStateChangeEvent) ProtoMessage() {}

func (x *MatchStateChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStateChangeEvent.ProtoReflect.Descriptor instead.
func (*MatchStateChangeEvent) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{2}
}

func (x *MatchStateChangeEvent) GetType() MatchStateChangeEvent_Type {
	if x != nil {
		return x.Type
	}
	return MatchStateChangeEvent_MatchPending
}

var File_match_proto protoreflect.FileDescriptor

var file_match_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a,
	0x12, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x38, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x6f, 0x74, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x10, 0x03, 0x22, 0xb2, 0x01, 0x0a, 0x13,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x22, 0x27, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x01, 0x22, 0x14, 0x0a, 0x04, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x05, 0x0a, 0x01, 0x41, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01, 0x42, 0x10, 0x01,
	0x22, 0xec, 0x01, 0x0a, 0x15, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65,
	0x42, 0x65, 0x67, 0x69, 0x6e, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x45,
	0x6e, 0x64, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x74, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x45, 0x6e, 0x64, 0x10, 0x08,
	0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x45, 0x78, 0x69, 0x74, 0x10, 0x09, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_match_proto_rawDescOnce sync.Once
	file_match_proto_rawDescData = file_match_proto_rawDesc
)

func file_match_proto_rawDescGZIP() []byte {
	file_match_proto_rawDescOnce.Do(func() {
		file_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_match_proto_rawDescData)
	})
	return file_match_proto_rawDescData
}

var file_match_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_match_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_match_proto_goTypes = []interface{}{
	(MatchMakingRequest_Type)(0),    // 0: MatchMakingRequest.Type
	(MatchMakingResponse_Type)(0),   // 1: MatchMakingResponse.Type
	(MatchMakingResponse_Role)(0),   // 2: MatchMakingResponse.Role
	(MatchStateChangeEvent_Type)(0), // 3: MatchStateChangeEvent.Type
	(*MatchMakingRequest)(nil),      // 4: MatchMakingRequest
	(*MatchMakingResponse)(nil),     // 5: MatchMakingResponse
	(*MatchStateChangeEvent)(nil),   // 6: MatchStateChangeEvent
}
var file_match_proto_depIdxs = []int32{
	0, // 0: MatchMakingRequest.type:type_name -> MatchMakingRequest.Type
	1, // 1: MatchMakingResponse.type:type_name -> MatchMakingResponse.Type
	2, // 2: MatchMakingResponse.role:type_name -> MatchMakingResponse.Role
	3, // 3: MatchStateChangeEvent.type:type_name -> MatchStateChangeEvent.Type
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_match_proto_init() }
func file_match_proto_init() {
	if File_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchMakingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchMakingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStateChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_match_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_proto_goTypes,
		DependencyIndexes: file_match_proto_depIdxs,
		EnumInfos:         file_match_proto_enumTypes,
		MessageInfos:      file_match_proto_msgTypes,
	}.Build()
	File_match_proto = out.File
	file_match_proto_rawDesc = nil
	file_match_proto_goTypes = nil
	file_match_proto_depIdxs = nil
}
