// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: match_making.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MatchMakingRequest_Type int32

const (
	MatchMakingRequest_Begin  MatchMakingRequest_Type = 0
	MatchMakingRequest_Cancel MatchMakingRequest_Type = 1
)

// Enum value maps for MatchMakingRequest_Type.
var (
	MatchMakingRequest_Type_name = map[int32]string{
		0: "Begin",
		1: "Cancel",
	}
	MatchMakingRequest_Type_value = map[string]int32{
		"Begin":  0,
		"Cancel": 1,
	}
)

func (x MatchMakingRequest_Type) Enum() *MatchMakingRequest_Type {
	p := new(MatchMakingRequest_Type)
	*p = x
	return p
}

func (x MatchMakingRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMakingRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_match_making_proto_enumTypes[0].Descriptor()
}

func (MatchMakingRequest_Type) Type() protoreflect.EnumType {
	return &file_match_making_proto_enumTypes[0]
}

func (x MatchMakingRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMakingRequest_Type.Descriptor instead.
func (MatchMakingRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_match_making_proto_rawDescGZIP(), []int{0, 0}
}

type MatchMakingResponse_Type int32

const (
	MatchMakingResponse_Ready        MatchMakingResponse_Type = 0
	MatchMakingResponse_NotAvailable MatchMakingResponse_Type = 1
)

// Enum value maps for MatchMakingResponse_Type.
var (
	MatchMakingResponse_Type_name = map[int32]string{
		0: "Ready",
		1: "NotAvailable",
	}
	MatchMakingResponse_Type_value = map[string]int32{
		"Ready":        0,
		"NotAvailable": 1,
	}
)

func (x MatchMakingResponse_Type) Enum() *MatchMakingResponse_Type {
	p := new(MatchMakingResponse_Type)
	*p = x
	return p
}

func (x MatchMakingResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMakingResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_match_making_proto_enumTypes[1].Descriptor()
}

func (MatchMakingResponse_Type) Type() protoreflect.EnumType {
	return &file_match_making_proto_enumTypes[1]
}

func (x MatchMakingResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMakingResponse_Type.Descriptor instead.
func (MatchMakingResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_match_making_proto_rawDescGZIP(), []int{1, 0}
}

type MatchMakingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MatchMakingRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=MatchMakingRequest_Type" json:"type,omitempty"`
}

func (x *MatchMakingRequest) Reset() {
	*x = MatchMakingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_making_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchMakingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMakingRequest) ProtoMessage() {}

func (x *MatchMakingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_making_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMakingRequest.ProtoReflect.Descriptor instead.
func (*MatchMakingRequest) Descriptor() ([]byte, []int) {
	return file_match_making_proto_rawDescGZIP(), []int{0}
}

func (x *MatchMakingRequest) GetType() MatchMakingRequest_Type {
	if x != nil {
		return x.Type
	}
	return MatchMakingRequest_Begin
}

type MatchMakingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MatchMakingResponse_Type `protobuf:"varint,1,opt,name=type,proto3,enum=MatchMakingResponse_Type" json:"type,omitempty"`
}

func (x *MatchMakingResponse) Reset() {
	*x = MatchMakingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_making_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchMakingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMakingResponse) ProtoMessage() {}

func (x *MatchMakingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_making_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMakingResponse.ProtoReflect.Descriptor instead.
func (*MatchMakingResponse) Descriptor() ([]byte, []int) {
	return file_match_making_proto_rawDescGZIP(), []int{1}
}

func (x *MatchMakingResponse) GetType() MatchMakingResponse_Type {
	if x != nil {
		return x.Type
	}
	return MatchMakingResponse_Ready
}

var File_match_making_proto protoreflect.FileDescriptor

var file_match_making_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x61, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x1d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x10, 0x01, 0x22, 0x69, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x23, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x10, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_match_making_proto_rawDescOnce sync.Once
	file_match_making_proto_rawDescData = file_match_making_proto_rawDesc
)

func file_match_making_proto_rawDescGZIP() []byte {
	file_match_making_proto_rawDescOnce.Do(func() {
		file_match_making_proto_rawDescData = protoimpl.X.CompressGZIP(file_match_making_proto_rawDescData)
	})
	return file_match_making_proto_rawDescData
}

var file_match_making_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_match_making_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_match_making_proto_goTypes = []interface{}{
	(MatchMakingRequest_Type)(0),  // 0: MatchMakingRequest.Type
	(MatchMakingResponse_Type)(0), // 1: MatchMakingResponse.Type
	(*MatchMakingRequest)(nil),    // 2: MatchMakingRequest
	(*MatchMakingResponse)(nil),   // 3: MatchMakingResponse
}
var file_match_making_proto_depIdxs = []int32{
	0, // 0: MatchMakingRequest.type:type_name -> MatchMakingRequest.Type
	1, // 1: MatchMakingResponse.type:type_name -> MatchMakingResponse.Type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_match_making_proto_init() }
func file_match_making_proto_init() {
	if File_match_making_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_match_making_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchMakingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_making_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchMakingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_match_making_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_making_proto_goTypes,
		DependencyIndexes: file_match_making_proto_depIdxs,
		EnumInfos:         file_match_making_proto_enumTypes,
		MessageInfos:      file_match_making_proto_msgTypes,
	}.Build()
	File_match_making_proto = out.File
	file_match_making_proto_rawDesc = nil
	file_match_making_proto_goTypes = nil
	file_match_making_proto_depIdxs = nil
}
